### ISSUE TITLE
Crash of ARKStatsExtractor when using ArkSavegameToolkit

### ISSUE THREAD

**Issue by ACCakut** [Flachdachs/ArkSavegameToolkit#1] opened 2018-11-12 13:25 UTC
I get an `System.InvalidCastException: Unable to cast object of type 'SavegameToolkit.Arrays.ArkArrayUnknown' to type 'SavegameToolkit.Arrays.ArkArrayStruct'.` if using ARK Smart Breeding.

Bug posted here: [https://github.com/cadon/ARKStatsExtractor/issues/828](https://github.com/cadon/ARKStatsExtractor/issues/828)

I hope it is ok for you to start a second issue here. I suppose, the bug is more relevant to ArkSavegameToolkit, since "Unknown" doesn't sound good and ark-tools works fine.

**Comment by Flachdachs** [comment] 2018-11-12 19:16
most likely not a bug of the Toolkit

**Comment by Flachdachs** [comment] 2018-11-12 22:32
Fixed in 5eb8c7e

**Closed by Flachdachs** 2018-11-12 22:32 UTC
Labels: bug
